import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

const translations = {
  ru: {
    dashboard: 'Сводка',
    users: 'Пользователи',
    bots: 'Мои Боты',
    settings: 'Настройки',
    account: 'Аккаунт',
    login: 'Войти',
    launchDemo: 'Запустить Демо',
    home: 'Главная',
    faq: 'FAQ',
    features: 'Возможности',
    pricing: 'Цена',
    contacts: 'Контакты',
    security: 'Безопасность',
    interface: 'Интерфейс',
    language: 'Язык',
    theme: 'Тема',
    greenTheme: 'Зеленая',
    blueTheme: 'Темно-синяя',
    whiteTheme: 'Темно-серая',
    russian: 'Русский',
    english: 'English',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Изменить',
    add: 'Добавить',
    close: 'Закрыть',
    loading: 'Загрузка...',
    apply: 'Применить',
    reset: 'Сбросить',
    search: 'Поиск',
    filter: 'Фильтры',
    send: 'Отправить',
    sending: 'Отправка...',
    refresh: 'Обновить',
    sync: 'Синхронизировать',
    syncing: 'Синхронизация...',
    loginTitle: 'Войдите в панель управления',
    username: 'Логин',
    password: 'Пароль',
    enterUsername: 'Введите логин',
    enterPassword: 'Введите пароль',
    enterLoginPassword: 'Введите логин и пароль',
    invalidCredentials: 'Неверный логин или пароль',
    dashboardTitle: 'Сводка',
    dashboardDescription: 'Обзор активности ваших ботов',
    totalUsers: 'Всего пользователей',
    newUsers: 'Новых пользователей',
    messages: 'Сообщений',
    addBot: 'Добавить бота',
    addFirstBot: 'Добавьте первого бота',
    addFirstBotText: 'Начните отслеживать аналитику, добавив вашего Telegram бота',
    timeRange: 'Период',
    today: 'Сегодня',
    day1: '1 день',
    days7: '7 дней',
    days30: '30 дней',
    days90: '90 дней',
    newUsersChart: 'Новые пользователи',
    messagesChart: 'Сообщения',
    allTime: 'Все время',
    activity: 'Активность',
    usersTitle: 'Пользователи',
    userList: 'Список всех пользователей вашего бота',
    broadcast: 'Рассылка',
    noUsers: 'Нет пользователей',
    noUsersText: 'Пользователей пока нет',
    noUsersDescription: 'Данные о пользователях появятся после подключения ботов и начала их использования',
    searchUsers: 'Поиск пользователей...',
    shown: 'Показано',
    of: 'из',
    usersCountText: 'Пользователей',
    blocked: 'Заблокирован',
    notBlocked: 'Не заблокирован',
    block: 'Заблокировать',
    unblock: 'Разблокировать',
    checkBlock: 'Проверить блокировку бота',
    chat: 'Чат',
    user: 'Пользователь',
    blockedUser: 'заблокирован',
    unblockedUser: 'разблокирован',
    checkBlockWarning: 'При проверке блокировки бота будет отправлено тестовое сообщение пользователю. Сообщение будет автоматически удалено после проверки.',
    dontShowAgain: 'Больше не показывать',
    continue: 'Продолжить',
    confirmBlock: 'Подтверждение блокировки',
    confirmBlockText: 'Вы уверены, что хотите',
    confirmBlockUser: 'этого пользователя?',
    blockUser: 'Заблокировать пользователя',
    unblockUser: 'Разблокировать пользователя',
    botFilter: 'Бот',
    genderFilter: 'Пол',
    premiumFilter: 'Премиум',
    blockingFilter: 'Блокировка',
    dateFilter: 'Дата',
    status: 'Статус',
    lastActivity: 'Последняя активность',
    actions: 'Действия',
    blockedBot: 'Заблокировал бота',
    warning: 'Предупреждение',
    filters: 'Фильтры',
    allBots: 'Все боты',
    gender: 'Пол',
    all: 'Все',
    male: 'Мужской',
    female: 'Женский',
    premium: 'Премиум',
    yes: 'Да',
    no: 'Нет',
    blocking: 'Блокировка',
    blockedUsers: 'Заблокированные',
    notBlockedUsers: 'Не заблокированные',
    activityDateFrom: 'Дата активности от',
    activityDateTo: 'Дата активности до',
    activeFilters: 'Активные фильтры',
    broadcastMessage: 'Рассылка сообщений',
    selectBots: 'Выберите ботов',
    enterMessage: 'Введите сообщение',
    recipients: 'Получателей',
    confirmSend: 'Подтверждение рассылки',
    confirmSendText: 'Вы уверены, что хотите отправить рассылку?',
    recipientsCount: 'Количество получателей',
    activeFiltersText: 'Активные фильтры',
    sendingProgress: 'Отправка...',
    sent: 'Отправлено',
    failed: 'Ошибок',
    of: 'из',
    broadcastSuccess: 'Рассылка завершена',
    broadcastError: 'Ошибка при рассылке',
    selectAtLeastOneBot: 'Выберите хотя бы одного бота',
    noRecipients: 'Нет пользователей для рассылки с выбранными фильтрами',
    enterMessageText: 'Введите сообщение',
    languageFilter: 'Язык',
    premiumFilter: 'Премиум',
    blockedFilter: 'Блокировка',
    allLanguages: 'Все языки',
    broadcastSettings: 'Настройки рассылки',
    selectAll: 'Выбрать все',
    deselectAll: 'Снять все',
    searchLanguage: 'Поиск языка...',
    message: 'Сообщение',
    total: 'Всего',
    errors: 'Ошибки',
    andMoreErrors: '...и еще',
    selectedBots: 'Выбрано ботов',
    languages: 'Языки',
    confirm: 'Подтвердить',
    botsTitle: 'Мои Боты',
    myBots: 'Мои Боты',
    noBots: 'У вас пока нет ботов',
    noBotsText: 'Добавьте первого бота, чтобы начать отслеживать аналитику',
    botName: 'Название бота',
    botToken: 'Токен бота',
    addBotTitle: 'Добавить бота',
    editBotTitle: 'Редактировать бота',
    verify: 'Проверить',
    verifying: 'Проверка...',
    fillRequired: 'Заполните обязательные поля',
    fillNameToken: 'Заполните обязательные поля: название и токен бота',
    syncAll: 'Синхронизировать все боты',
    syncAllBots: 'Синхронизировать все',
    syncBot: 'Синхронизировать',
    deleteBot: 'Удалить бота',
    confirmDelete: 'Подтверждение удаления',
    confirmDeleteText: 'Вы уверены, что хотите удалить этого бота?',
    syncSuccess: 'Синхронизация завершена',
    syncError: 'Ошибка при синхронизации',
    active: 'Активен',
    inactive: 'Неактивен',
    usersCount: 'Пользователей',
    manageBots: 'Управление вашими Telegram ботами',
    allBots: 'Все боты',
    botFound: 'Бот найден',
    noUsername: 'без username',
    getTokenFromBotFather: 'Получите токен у @BotFather в Telegram. Токен будет использоваться для получения данных.',
    successfullySynced: 'успешно синхронизирован',
    processedEvents: 'Обработано событий',
    totalUpdates: 'Всего обновлений',
    bot: 'Бот',
    sendMessage: 'Отправить сообщение',
    deleteMessage: 'Удалить сообщение',
    confirmDeleteMessage: 'Подтверждение удаления',
    confirmDeleteMessageText: 'Вы уверены, что хотите удалить это сообщение? Это действие нельзя отменить.',
    noMessages: 'Нет сообщений',
    sendError: 'Ошибка отправки',
    error: 'Ошибка',
    settings: 'Настройки',
    settingsDescription: 'Управление настройками вашего аккаунта',
    changePassword: 'Смена пароля',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    changePasswordButton: 'Изменить пароль',
    logout: 'Выйти',
    logoutTitle: 'Выход из аккаунта',
    logoutText: 'Выйти из текущего аккаунта. Вы сможете войти снова, используя сохраненные учетные данные.',
    logoutConfirm: 'Подтверждение выхода',
    logoutConfirmText: 'Вы уверены, что хотите выйти из аккаунта? Вы сможете войти снова, используя сохраненные учетные данные.',
    userManagement: 'Управление пользователями',
    addUser: 'Добавить пользователя',
    editUser: 'Редактировать пользователя',
    noUsersAdded: 'Нет добавленных пользователей',
    created: 'Создан',
    unlimitedAccess: 'Доступ бесконечный',
    accessExpired: 'Доступ истек',
    accessUntil: 'Доступ до',
    daysLeft: 'осталось',
    days: 'дн.',
    loginField: 'Логин',
    passwordField: 'Пароль',
    enterLogin: 'Введите логин',
    enterPasswordField: 'Введите пароль',
    unlimitedAccessCheckbox: 'Бесконечный доступ',
    accessPeriod: 'Срок доступа (дней)',
  },
  en: {
    dashboard: 'Dashboard',
    users: 'Users',
    bots: 'My Bots',
    settings: 'Settings',
    account: 'Account',
    login: 'Login',
    launchDemo: 'Launch Demo',
    home: 'Home',
    faq: 'FAQ',
    features: 'Features',
    pricing: 'Pricing',
    contacts: 'Contacts',
    security: 'Security',
    interface: 'Interface',
    language: 'Language',
    theme: 'Theme',
    greenTheme: 'Green',
    blueTheme: 'Dark Blue',
    whiteTheme: 'Dark Gray',
    russian: 'Русский',
    english: 'English',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',
    loading: 'Loading...',
    apply: 'Apply',
    reset: 'Reset',
    search: 'Search',
    filter: 'Filters',
    send: 'Send',
    sending: 'Sending...',
    refresh: 'Refresh',
    sync: 'Sync',
    syncing: 'Syncing...',
    loginTitle: 'Login to control panel',
    username: 'Username',
    password: 'Password',
    enterUsername: 'Enter username',
    enterPassword: 'Enter password',
    enterLoginPassword: 'Enter username and password',
    invalidCredentials: 'Invalid username or password',
    dashboardTitle: 'Dashboard',
    dashboardDescription: 'Overview of your bots activity',
    totalUsers: 'Total Users',
    newUsers: 'New Users',
    messages: 'Messages',
    addBot: 'Add Bot',
    addFirstBot: 'Add your first bot',
    addFirstBotText: 'Start tracking analytics by adding your Telegram bot',
    timeRange: 'Time Range',
    today: 'Today',
    day1: '1 day',
    days7: '7 days',
    days30: '30 days',
    days90: '90 days',
    newUsersChart: 'New Users',
    messagesChart: 'Messages',
    allTime: 'All Time',
    activity: 'Activity',
    usersTitle: 'Users',
    userList: 'List of all your bot users',
    broadcast: 'Broadcast',
    noUsers: 'No users',
    noUsersText: 'No users yet',
    noUsersDescription: 'User data will appear after connecting bots and starting to use them',
    searchUsers: 'Search users...',
    shown: 'Shown',
    of: 'of',
    usersCountText: 'Users',
    blocked: 'Blocked',
    notBlocked: 'Not Blocked',
    block: 'Block',
    unblock: 'Unblock',
    checkBlock: 'Check bot blocking',
    chat: 'Chat',
    user: 'User',
    blockedUser: 'blocked',
    unblockedUser: 'unblocked',
    checkBlockWarning: 'When checking bot blocking, a test message will be sent to the user. The message will be automatically deleted after checking.',
    dontShowAgain: "Don't show again",
    continue: 'Continue',
    confirmBlock: 'Block Confirmation',
    confirmBlockText: 'Are you sure you want to',
    confirmBlockUser: 'this user?',
    blockUser: 'Block User',
    unblockUser: 'Unblock User',
    botFilter: 'Bot',
    genderFilter: 'Gender',
    premiumFilter: 'Premium',
    blockingFilter: 'Blocking',
    dateFilter: 'Date',
    status: 'Status',
    lastActivity: 'Last Activity',
    actions: 'Actions',
    blockedBot: 'Blocked Bot',
    warning: 'Warning',
    filters: 'Filters',
    allBots: 'All Bots',
    gender: 'Gender',
    all: 'All',
    male: 'Male',
    female: 'Female',
    premium: 'Premium',
    yes: 'Yes',
    no: 'No',
    blocking: 'Blocking',
    blockedUsers: 'Blocked',
    notBlockedUsers: 'Not Blocked',
    activityDateFrom: 'Activity Date From',
    activityDateTo: 'Activity Date To',
    activeFilters: 'Active Filters',
    broadcastMessage: 'Broadcast Message',
    selectBots: 'Select Bots',
    enterMessage: 'Enter message',
    recipients: 'Recipients',
    confirmSend: 'Send Confirmation',
    confirmSendText: 'Are you sure you want to send the broadcast?',
    recipientsCount: 'Number of recipients',
    activeFiltersText: 'Active filters',
    sendingProgress: 'Sending...',
    sent: 'Sent',
    failed: 'Failed',
    of: 'of',
    broadcastSuccess: 'Broadcast completed',
    broadcastError: 'Broadcast error',
    selectAtLeastOneBot: 'Select at least one bot',
    noRecipients: 'No users for broadcast with selected filters',
    enterMessageText: 'Enter message',
    languageFilter: 'Language',
    premiumFilter: 'Premium',
    blockedFilter: 'Blocking',
    allLanguages: 'All Languages',
    broadcastSettings: 'Broadcast Settings',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    searchLanguage: 'Search language...',
    message: 'Message',
    total: 'Total',
    errors: 'Errors',
    andMoreErrors: '...and',
    selectedBots: 'Selected Bots',
    languages: 'Languages',
    confirm: 'Confirm',
    botsTitle: 'My Bots',
    myBots: 'My Bots',
    noBots: 'You have no bots yet',
    noBotsText: 'Add your first bot to start tracking analytics',
    botName: 'Bot Name',
    botToken: 'Bot Token',
    addBotTitle: 'Add Bot',
    editBotTitle: 'Edit Bot',
    verify: 'Verify',
    verifying: 'Verifying...',
    fillRequired: 'Fill in required fields',
    fillNameToken: 'Fill in required fields: bot name and token',
    syncAll: 'Sync All Bots',
    syncAllBots: 'Sync All',
    syncBot: 'Sync',
    deleteBot: 'Delete Bot',
    confirmDelete: 'Delete Confirmation',
    confirmDeleteText: 'Are you sure you want to delete this bot?',
    syncSuccess: 'Sync completed',
    syncError: 'Sync error',
    active: 'Active',
    inactive: 'Inactive',
    usersCount: 'Users',
    manageBots: 'Manage your Telegram bots',
    allBots: 'All Bots',
    botFound: 'Bot found',
    noUsername: 'no username',
    getTokenFromBotFather: 'Get token from @BotFather in Telegram. The token will be used to fetch data.',
    successfullySynced: 'successfully synced',
    processedEvents: 'Processed Events',
    totalUpdates: 'Total Updates',
    bot: 'Bot',
    sendMessage: 'Send Message',
    deleteMessage: 'Delete Message',
    confirmDeleteMessage: 'Delete Confirmation',
    confirmDeleteMessageText: 'Are you sure you want to delete this message? This action cannot be undone.',
    noMessages: 'No messages',
    sendError: 'Send Error',
    error: 'Error',
    settings: 'Settings',
    settingsDescription: 'Manage your account settings',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    changePasswordButton: 'Change Password',
    logout: 'Logout',
    logoutTitle: 'Logout',
    logoutText: 'Log out of your current account. You can log in again using saved credentials.',
    logoutConfirm: 'Logout Confirmation',
    logoutConfirmText: 'Are you sure you want to log out? You can log in again using saved credentials.',
    userManagement: 'User Management',
    addUser: 'Add User',
    editUser: 'Edit User',
    noUsersAdded: 'No users added',
    created: 'Created',
    unlimitedAccess: 'Unlimited Access',
    accessExpired: 'Access Expired',
    accessUntil: 'Access Until',
    daysLeft: 'days left',
    days: 'days',
    loginField: 'Login',
    passwordField: 'Password',
    enterLogin: 'Enter login',
    enterPasswordField: 'Enter password',
    unlimitedAccessCheckbox: 'Unlimited Access',
    accessPeriod: 'Access Period (days)',
  },
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('botpanel_language')
    if (saved) {
      return saved
    }
    return 'en'
  })

  useEffect(() => {
    localStorage.setItem('botpanel_language', language)
  }, [language])

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage)
  }

  const t = (key) => {
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider
      value={{
        language,
        changeLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  )
}
